export interface AdditionalSource {
  name: string;
  url: string;
  id?: string;
}

export interface DataSourceMetadata {
  title: string;
  agency: string;
  datasetName: string;
  datasetId?: string;
  url: string;
  retrievalSummary: string;
  generationSummary: string;
  frequency?: string;
  additionalSources?: AdditionalSource[];
}

export const DATA_SOURCES: Record<string, DataSourceMetadata> = {
  hdb: {
    title: 'HDB Resale Prices & Housing Analytics',
    agency: 'Housing & Development Board (HDB)',
    datasetName: 'Resale Flat Prices (Jan 2017 onwards)',
    datasetId: 'd_8b84c4ee58e3cfc0ece0d773c8ca6abc',
    url: 'https://data.gov.sg/datasets/d_8b84c4ee58e3cfc0ece0d773c8ca6abc/view',
    retrievalSummary:
      'Recent monthly transactions are fetched live via the data.gov.sg Datastore API (resource d_8b84c4ee58e3cfc0ece0d773c8ca6abc) and merged with official historical records spanning back to 1990.',
    generationSummary:
      'Raw transactions are normalized to calculate Price per Square Foot (PSF), remaining lease years, YoY price indices, estate-level median breakdowns, and lease decay curves.',
    frequency: 'Monthly / Live API',
    additionalSources: [
      {
        name: 'HDB Historical Resale Price Index (2009-Q1=100)',
        url: 'https://data.gov.sg/datasets/d_16c57919e0758ebcf5594b29f0469b82/view',
        id: 'd_16c57919e0758ebcf5594b29f0469b82'
      }
    ]
  },
  income: {
    title: 'Household Income & Wealth Distribution',
    agency: 'Singapore Department of Statistics (DOS)',
    datasetName: 'Resident Employed Households Monthly Household Income from Work',
    datasetId: 'd_c74ebe613db891d25e4836aaf98d7a47',
    url: 'https://data.gov.sg/datasets/d_c74ebe613db891d25e4836aaf98d7a47/view',
    retrievalSummary:
      'Retrieved dynamically via data.gov.sg Datastore Search API across four official SingStat tables covering median/average incomes, decile breakdowns, dwelling types, and CPI.',
    generationSummary:
      'Real median income is dynamically generated by deflating nominal wages against the General Consumer Price Index (base year 2008). Income deciles (1st to 10th) and housing segments are aligned across historical annual surveys.',
    frequency: 'Annual Survey',
    additionalSources: [
      {
        name: 'Household Income by Deciles',
        url: 'https://data.gov.sg/datasets/d_b37bc6f05c76337ad51aefddf0b7c888/view',
        id: 'd_b37bc6f05c76337ad51aefddf0b7c888'
      },
      {
        name: 'Consumer Price Index (CPI)',
        url: 'https://data.gov.sg/datasets/d_b7c2e74824c179995d15d73eac845ba1/view',
        id: 'd_b7c2e74824c179995d15d73eac845ba1'
      },
      {
        name: 'Household Income by Dwelling Type',
        url: 'https://data.gov.sg/datasets/d_ce5d8bb5c34f6b78b5b2f1fab09ccbce/view',
        id: 'd_ce5d8bb5c34f6b78b5b2f1fab09ccbce'
      }
    ]
  },
  employment: {
    title: 'Economy & Labour Market',
    agency: 'Ministry of Manpower (MOM)',
    datasetName: 'Unemployment Rate (Seasonally Adjusted, End-June)',
    datasetId: 'd_285a079d823a1cc22dffb9cac325f81a',
    url: 'https://data.gov.sg/datasets/d_285a079d823a1cc22dffb9cac325f81a/view',
    retrievalSummary:
      'Extracted directly from data.gov.sg Datastore API querying official Ministry of Manpower annual unemployment surveys.',
    generationSummary:
      'Extracts both Overall and Resident seasonally adjusted unemployment series from 1992 to the present, parses non-numeric markers, derives the resident-overall gap, and calculates Year-on-Year percentage point movements.',
    frequency: 'Annual / Semi-annual'
  },
  ges: {
    title: 'Graduate Employment Survey',
    agency: 'Ministry of Education (MOE)',
    datasetName: 'Graduate Employment Survey - NTU, NUS, SIT, SMU, SUSS & SUTD',
    datasetId: 'd_3c55210de27fcccda2ed0c63fdd2b352',
    url: 'https://data.gov.sg/datasets/d_3c55210de27fcccda2ed0c63fdd2b352/view',
    retrievalSummary:
      'Retrieved from data.gov.sg Datastore API querying official annual survey publications conducted across all autonomous universities.',
    generationSummary:
      'Raw records are sanitized to remove footnote annotations, parsed into numeric salaries and full-time permanent employment rates, categorized into degree clusters (Healthcare, Law, Computing, Engineering, Business, Arts), and evaluated for interquartile ranges.',
    frequency: 'Annual Survey'
  },
  birthRates: {
    title: 'Birth Rates & Fertility Trends',
    agency: 'Singapore Department of Statistics (DOS)',
    datasetName: 'Total Fertility Rate by Ethnic Group',
    datasetId: 'd_e39eeaeadb571c0d0725ef1eec48d166',
    url: 'https://data.gov.sg/datasets/d_e39eeaeadb571c0d0725ef1eec48d166/view',
    retrievalSummary:
      'Fetched from data.gov.sg Datastore Search API combining historical fertility rate records with first-marriage age statistics from SingStat.',
    generationSummary:
      'Harmonizes longitudinal Total Fertility Rate (TFR) data from 1960 onwards with ethnic breakdowns (Chinese, Malay, Indian) and correlates them with rising median ages at first marriage for resident brides and grooms.',
    frequency: 'Annual Publication',
    additionalSources: [
      {
        name: 'Median Age at First Marriage',
        url: 'https://data.gov.sg/datasets/d_48bab86448603efe0a6f0fcd6aa545b6/view',
        id: 'd_48bab86448603efe0a6f0fcd6aa545b6'
      }
    ]
  },
  coe: {
    title: 'Certificate of Entitlement (COE) Bidding',
    agency: 'Land Transport Authority (LTA)',
    datasetName: 'Certificate of Entitlement (COE) Bidding Results',
    datasetId: 'd_69b3380ad7e51aff3a7dcc84eba52b8a',
    url: 'https://data.gov.sg/datasets/d_69b3380ad7e51aff3a7dcc84eba52b8a/view',
    retrievalSummary:
      'Queried via data.gov.sg Datastore Search API with an hourly in-memory cache to retrieve every bidding exercise since 2010.',
    generationSummary:
      'Bidding exercises across Categories A through E are chronologically sequenced to compute bidding round premium changes, quota premiums, bid-to-quota demand ratios, and historical volatility trends.',
    frequency: 'Twice Monthly (Post-Bidding)'
  },
  commuting: {
    title: 'Public Transport Ridership',
    agency: 'Land Transport Authority (LTA)',
    datasetName: 'Public Transport Ridership (Average Daily)',
    datasetId: 'd_75248cf2fbf340de6a746dc91ec9223c',
    url: 'https://data.gov.sg/datasets/d_75248cf2fbf340de6a746dc91ec9223c/view',
    retrievalSummary:
      'Resolved dynamically via the data.gov.sg Poll-Download API (api-open.data.gov.sg/v1/public/api/datasets/d_75248cf2fbf340de6a746dc91ec9223c/poll-download) and parsed from CSV.',
    generationSummary:
      'Aggregates average daily passenger volume across MRT, LRT, and Public Bus networks from 1995 to 2024, computing transit modal splits, rail-to-bus ratios, and Year-on-Year ridership growth.',
    frequency: 'Annual Publication'
  },
  climate: {
    title: 'Singapore Climate Change & Weather',
    agency: 'Meteorological Service Singapore (MSS) / NEA',
    datasetName: 'Surface Air Temperature (Monthly Mean)',
    datasetId: 'd_755290a24afe70c8f9e8bcbf9f251573',
    url: 'https://data.gov.sg/datasets/d_755290a24afe70c8f9e8bcbf9f251573/view',
    retrievalSummary:
      'Fetched concurrently via data.gov.sg Datastore API for both monthly surface temperatures and monthly total rainfall.',
    generationSummary:
      'Merges monthly temperature and precipitation data, aggregates them into annual averages and decade-by-decade climate trends (1980s–2020s), and compares them against historical baseline benchmarks.',
    frequency: 'Monthly Publication',
    additionalSources: [
      {
        name: 'Total Rainfall Monthly',
        url: 'https://data.gov.sg/datasets/d_b16d06b83473fdfcc92ed9d37b66ba58/view',
        id: 'd_b16d06b83473fdfcc92ed9d37b66ba58'
      }
    ]
  },
  airQuality: {
    title: 'Air Quality & Haze Monitoring',
    agency: 'National Environment Agency (NEA)',
    datasetName: 'Pollutant Standards Index (PSI) & PM2.5',
    url: 'https://data.gov.sg/datasets?query=Pollutant+Standards+Index',
    retrievalSummary:
      'Streamed live directly from NEA open environmental APIs on data.gov.sg with automated client polling.',
    generationSummary:
      'Parses real-time 24-hr PSI and 1-hr PM2.5 readings across Singapore’s five geographic regions (North, South, East, West, Central), calculates national peak/average metrics, and evaluates them against NEA health advisory bands.',
    frequency: 'Hourly (Real-Time)',
    additionalSources: [
      {
        name: 'Pollutant Standards Index (PSI) Datasets',
        url: 'https://data.gov.sg/datasets?query=Pollutant+Standards+Index'
      },
      {
        name: 'Air Pollutant - Particulate Matter PM2.5',
        url: 'https://data.gov.sg/datasets/d_397fe8de643aea9927bdee32e49307ff/view',
        id: 'd_397fe8de643aea9927bdee32e49307ff'
      },
      {
        name: 'Particulate Matter (PM2.5) Datasets',
        url: 'https://data.gov.sg/datasets?query=PM2.5'
      }
    ]
  }
};
